server.port=9099
spring.application.name=uandesnueva

spring.datasource.url=jdbc:postgresql://pg-2000e19d-gmproyect-dd03.b.aivencloud.com:25688/defaultdb?ssl=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_06t6KaK_ospafOkf5cK
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



